#!/bin/bash

IFS=$' \t\n'

# set -xv
set -o nounset
set -o errexit
set -o pipefail
set -o noclobber

usage_and_exit(){
   {
      echo "${0##*/}" '<name>'
   } >&2
   exit "${1:-1}"
}


if [[ $# -ne 1 ]] || [[ $1 = -h ]] || [[ $1 = --help ]]; then
   usage_and_exit
fi

echo "$(dirname "$1")"/"$("$(cd "${0%/*}"; pwd -P)"/ymdhms.sh)"_"${1##*/}"
