#!/bin/bash

IFS=$' \t\n'

# set -xv
set -o nounset
set -o errexit
set -o noclobber

usage_and_exit(){
   {
      echo "${0##*/}" '<name>'
   } >&2
   exit "${1}"
}


if [[ "$#" -ne 1 ]] || [[ "$1" = -h ]] || [[ "$1" = --help ]]; then
   usage_and_exit 1
fi

echo "$(dirname -- "$1")"/"$(date +'%y%m%d%H%M%S')"_"${1##*/}"
