#!/bin/bash

IFS=$' \t\n'

# set -xv
set -o nounset
set -o errexit
set -o pipefail
set -o noclobber


usage_and_exit(){
   {
      echo "$(basename "$0")" PATTERN
   } > /dev/stderr
   exit 1
}

if [[ $# -eq 0 ]]; then
   usage_and_exit
fi

grep --color=auto "$@" "${HOME}"/.bash_history
