#!/bin/bash

IFS=$' \t\n'

# set -xv
set -o nounset
set -o errexit
set -o noclobber


usage_and_exit(){
   {
      echo "${0##*/}" '<pattern>'
   } > /dev/stderr
   exit 1
}

if [ "$#" -eq 0 ]; then
   usage_and_exit
fi


grep --color=auto "$@" "${HISTFILE:-"$HOME"/.bash_history}"
