#!/bin/bash
# @(#) create a junk file

IFS=$' \t\n'

# set -xv
set -o nounset
set -o errexit
set -o noclobber

usage_and_exit(){
   {
      echo "${0##*/}" '[<prefix>] [<suffix>]'
   } > /dev/stderr
   exit "${1:-1}"
}

readonly base_name=delete_me

if [ "$#" -eq 0 ]; then
   readonly file=./"${base_name}".tmp
elif [ "$#" -eq 1 ]; then
   readonly file=./"${base_name}"."${1}"
elif [ "$#" -eq 2 ]; then
   readonly file="${1}"/"${base_name}"."${2}"
else
   usage_and_exit 1
fi
"${EDITOR}" "${file}"
echo "${file}"
