#!/bin/bash

IFS=$' \t\n'

# set -xv
set -o nounset
set -o errexit
set -o noclobber

usage_and_exit(){
   {
      echo '# view command internal'
      echo "${0##*/}" '<command>'
   } > /dev/stderr
   exit "${1}"
}

if [[ "$#" -ne 1 ]]; then
   usage_and_exit 1
fi

less -- "$(which -- "$1")"
