#!/bin/bash

IFS=$' \t\n'

# set -xv
set -o nounset
set -o errexit
set -o pipefail
set -o noclobber

usage_and_exit(){
   {
      echo "$(basename "${0}")" '<dir>'
   } >&2
   exit "${1:-1}"
}


if [[ $# -ne 1 ]] || [[ $1 = -h ]] || [[ $1 = --help ]]; then
   usage_and_exit
fi

dir="$("$(cd "${0%/*}"; pwd -P)"/fnm "$1")"
mkdir -p "${dir}"
echo "${dir}"
