#!/bin/bash

IFS=$' \t\n'

# set -xv
set -o nounset
set -o errexit
set -o pipefail
set -o noclobber

usage_and_exit(){
   {
      echo "${0##*/}" '<dir>'
   } >&2
   exit "${1}"
}


if [[ $# -ne 1 ]] || [[ $1 = -h ]] || [[ $1 = --help ]]; then
   usage_and_exit 1
fi

dir="$("${0%/*}"/fnm "$1")"
mkdir -p "${dir}"
echo "${dir}"
