#!/bin/bash

# set -xv
set -o nounset
set -o errexit
set -o noclobber

usage_and_exit(){
   echo "${0##*/}" '<file>' > /dev/stderr
   exit "${1}"
}

if [[ "$#" -ne 1 ]] || [[ "$1" = -h ]] || [[ "$1" = --help ]]; then
   usage_and_exit 1
fi

readonly THIS_DIR="${0%/*}"
"${THIS_DIR}"/e "$("${THIS_DIR}"/tfnm "$1")"
