#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

if [[ ${#} -eq 0 ]]; then
    echo "${0}" FILES DIRS 1>&2
    exit 1
fi

readonly my_trash_dir="${MY_TRASH_DIR:-"${HOME}"/d/trash}"
readonly base_dir="${my_trash_dir}"/"$(date +'%y%m%d%H%M%S%N')"

mkdir -p "$base_dir"
mv --backup=numbered -- "$@" "$base_dir"
