#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

if [[ ${#} -eq 0 ]]; then
    echo "${0}" FILES DIRS 1>&2
    exit 1
fi

readonly my_trash_dir="${MY_TRASH_DIR:-"${HOME}"/d/trash}"
readonly base_dir="${my_trash_dir}"/"$(date +'%FT%T.%N%z')"

i=0
for f in "$@"
do
   dir="${base_dir}"/"$((i++))"
   mkdir -p "${dir}"
   mv -- "$f" "${dir}"
done
