#!/bin/sh

set -o nounset
set -o errexit

if [ "$#" -eq 0 ]; then
   echo "$0" '<file>...' 1>&2
   exit 1
fi
readonly my_trash_dir="${MY_TRASH_DIR:-"${HOME}"/d/trash}"
readonly base_dir="${my_trash_dir}"/"$(date +'%y%m%d%H%M%S%N')"

mkdir -p -- "$base_dir"
for f in "$@"
do
   tmp__="$base_dir/$(basename -- "$f")"
   while [ -e "$tmp__" ]
   do
      tmp__="$tmp__"_
   done
   mv -- "$f" "$tmp__"
done
