name: ci
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - run: |
        set -xv
        set -o nounset
        set -o errexit
        set -o pipefail
        set -o noclobber
        sudo apt update
        sudo apt install shellcheck git
        shellcheck -o all $(git ls-files | grep -v Makefile | grep -v README.md)
