name: ci
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        set -xv
        set -o nounset
        set -o errexit
        set -o pipefail
        set -o noclobber
        sudo apt update
        sudo apt install shellcheck git
    - run: |
        set -xv
        set -o nounset
        set -o errexit
        set -o pipefail
        set -o noclobber
        shellcheck -o all $(git grep -l '#!/bin/.*sh' | grep -v .github/)
